/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CertChainRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCertificate"
      | "getIssuer"
      | "isIssuer"
      | "issueCertificate"
      | "issueCertificateAuto"
      | "protocolId"
      | "registerIssuer"
      | "restoreCertificate"
      | "revokeCertificate"
      | "tipForView"
      | "updateIssuerMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateIssued"
      | "CertificateRestored"
      | "CertificateRevoked"
      | "IssuerRegistered"
      | "IssuerUpdated"
      | "TipPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [AddressLike, string, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificateAuto",
    values: [AddressLike, string, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerIssuer",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "restoreCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCertificate",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tipForView",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIssuerMetadata",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIssuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificateAuto",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restoreCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tipForView", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateIssuerMetadata",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    certId: BytesLike,
    issuer: AddressLike,
    recipient: AddressLike,
    cid: string,
    issuedAt: BigNumberish,
    validUntil: BigNumberish
  ];
  export type OutputTuple = [
    certId: string,
    issuer: string,
    recipient: string,
    cid: string,
    issuedAt: bigint,
    validUntil: bigint
  ];
  export interface OutputObject {
    certId: string;
    issuer: string;
    recipient: string;
    cid: string;
    issuedAt: bigint;
    validUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRestoredEvent {
  export type InputTuple = [
    certId: BytesLike,
    issuer: AddressLike,
    restoredAt: BigNumberish
  ];
  export type OutputTuple = [
    certId: string,
    issuer: string,
    restoredAt: bigint
  ];
  export interface OutputObject {
    certId: string;
    issuer: string;
    restoredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateRevokedEvent {
  export type InputTuple = [
    certId: BytesLike,
    issuer: AddressLike,
    reason: string,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    certId: string,
    issuer: string,
    reason: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    certId: string;
    issuer: string;
    reason: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRegisteredEvent {
  export type InputTuple = [
    issuer: AddressLike,
    name: string,
    metadataURI: string
  ];
  export type OutputTuple = [issuer: string, name: string, metadataURI: string];
  export interface OutputObject {
    issuer: string;
    name: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerUpdatedEvent {
  export type InputTuple = [issuer: AddressLike, metadataURI: string];
  export type OutputTuple = [issuer: string, metadataURI: string];
  export interface OutputObject {
    issuer: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TipPaidEvent {
  export type InputTuple = [
    certId: BytesLike,
    payer: AddressLike,
    amount: BigNumberish,
    paidAt: BigNumberish
  ];
  export type OutputTuple = [
    certId: string,
    payer: string,
    amount: bigint,
    paidAt: bigint
  ];
  export interface OutputObject {
    certId: string;
    payer: string;
    amount: bigint;
    paidAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertChainRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertChainRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertChainRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCertificate: TypedContractMethod<
    [certId: BytesLike],
    [
      [string, string, string, string, bigint, bigint, string, string] & {
        outCertId: string;
        issuer: string;
        owner: string;
        cid: string;
        issuedAt: bigint;
        validUntil: bigint;
        revoked: string;
        courseTag: string;
      }
    ],
    "view"
  >;

  getIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [[string, string] & { name: string; metadataURI: string }],
    "view"
  >;

  isIssuer: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  issueCertificate: TypedContractMethod<
    [
      recipient: AddressLike,
      cid: string,
      certId: BytesLike,
      validUntil: BigNumberish,
      courseTagExternal: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  issueCertificateAuto: TypedContractMethod<
    [
      recipient: AddressLike,
      cid: string,
      validUntil: BigNumberish,
      courseTagExternal: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerIssuer: TypedContractMethod<
    [name: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  restoreCertificate: TypedContractMethod<
    [certId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeCertificate: TypedContractMethod<
    [certId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  tipForView: TypedContractMethod<[certId: BytesLike], [void], "payable">;

  updateIssuerMetadata: TypedContractMethod<
    [issuer: AddressLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [certId: BytesLike],
    [
      [string, string, string, string, bigint, bigint, string, string] & {
        outCertId: string;
        issuer: string;
        owner: string;
        cid: string;
        issuedAt: bigint;
        validUntil: bigint;
        revoked: string;
        courseTag: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIssuer"
  ): TypedContractMethod<
    [issuer: AddressLike],
    [[string, string] & { name: string; metadataURI: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isIssuer"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      cid: string,
      certId: BytesLike,
      validUntil: BigNumberish,
      courseTagExternal: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueCertificateAuto"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      cid: string,
      validUntil: BigNumberish,
      courseTagExternal: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerIssuer"
  ): TypedContractMethod<
    [name: string, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "restoreCertificate"
  ): TypedContractMethod<[certId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCertificate"
  ): TypedContractMethod<
    [certId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tipForView"
  ): TypedContractMethod<[certId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "updateIssuerMetadata"
  ): TypedContractMethod<
    [issuer: AddressLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRestored"
  ): TypedContractEvent<
    CertificateRestoredEvent.InputTuple,
    CertificateRestoredEvent.OutputTuple,
    CertificateRestoredEvent.OutputObject
  >;
  getEvent(
    key: "CertificateRevoked"
  ): TypedContractEvent<
    CertificateRevokedEvent.InputTuple,
    CertificateRevokedEvent.OutputTuple,
    CertificateRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRegistered"
  ): TypedContractEvent<
    IssuerRegisteredEvent.InputTuple,
    IssuerRegisteredEvent.OutputTuple,
    IssuerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IssuerUpdated"
  ): TypedContractEvent<
    IssuerUpdatedEvent.InputTuple,
    IssuerUpdatedEvent.OutputTuple,
    IssuerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TipPaid"
  ): TypedContractEvent<
    TipPaidEvent.InputTuple,
    TipPaidEvent.OutputTuple,
    TipPaidEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(bytes32,address,address,string,uint256,uint256)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;

    "CertificateRestored(bytes32,address,uint256)": TypedContractEvent<
      CertificateRestoredEvent.InputTuple,
      CertificateRestoredEvent.OutputTuple,
      CertificateRestoredEvent.OutputObject
    >;
    CertificateRestored: TypedContractEvent<
      CertificateRestoredEvent.InputTuple,
      CertificateRestoredEvent.OutputTuple,
      CertificateRestoredEvent.OutputObject
    >;

    "CertificateRevoked(bytes32,address,string,uint256)": TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;
    CertificateRevoked: TypedContractEvent<
      CertificateRevokedEvent.InputTuple,
      CertificateRevokedEvent.OutputTuple,
      CertificateRevokedEvent.OutputObject
    >;

    "IssuerRegistered(address,string,string)": TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;
    IssuerRegistered: TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;

    "IssuerUpdated(address,string)": TypedContractEvent<
      IssuerUpdatedEvent.InputTuple,
      IssuerUpdatedEvent.OutputTuple,
      IssuerUpdatedEvent.OutputObject
    >;
    IssuerUpdated: TypedContractEvent<
      IssuerUpdatedEvent.InputTuple,
      IssuerUpdatedEvent.OutputTuple,
      IssuerUpdatedEvent.OutputObject
    >;

    "TipPaid(bytes32,address,uint256,uint256)": TypedContractEvent<
      TipPaidEvent.InputTuple,
      TipPaidEvent.OutputTuple,
      TipPaidEvent.OutputObject
    >;
    TipPaid: TypedContractEvent<
      TipPaidEvent.InputTuple,
      TipPaidEvent.OutputTuple,
      TipPaidEvent.OutputObject
    >;
  };
}
